[package]
name = "terminal_rhythm_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
num-traits = "0.2.15"
rand = "0.8.5"